name: Digital_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
- main
pool:
  name: Default

variables:
  buildPlatform: 'Any CPU' 
  buildConfiguration: 'Release'
  solution: '**/DigitalSignature.sln'

steps:
- task: NuGetToolInstaller@1
  name: 'NuGetToolInstaller'
  displayName: 'NuGet tool installer'